eureka:
    client:
        instance:
            preferIpAddress: true
        serviceUrl:
            defaultZone: http://localhost:8761/eureka
server:
    port: 9090
spring:
    application:
        name: productCatalog
    data:
        mongodb:
            database: ProductDB
            host: localhost
            port: 27017
        rest:
            base-path: /api/productCatalog